# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.vouchervresponse import VOUCHERVRESPONSE

class TestVOUCHERVRESPONSE(unittest.TestCase):
    """VOUCHERVRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VOUCHERVRESPONSE:
        """Test VOUCHERVRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VOUCHERVRESPONSE`
        """
        model = VOUCHERVRESPONSE()
        if include_optional:
            return VOUCHERVRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = [
                    gotit_api_python_sdk.models.voucher_v.VOUCHER_V(
                        order_name = 'Got It Promotion - Jul 2023', 
                        vouchers = [
                            gotit_api_python_sdk.models.voucher_v_schema.VOUCHER_V_SCHEMA(
                                transaction_ref_id = '1000007_123abc', 
                                voucher_code = '4142468304', 
                                voucher_link = 'https://v-stg.gotit.vn/b51r4XtA', 
                                voucher_link_code = 'b51r4XtA', 
                                voucher_image_link = 'https://v-stg.gotit.vn/save-voucher/vi/eyJpdiI6Ii80QVJaOXNmS0lBUmw3c283SjZ4amc9PSIsInZhbHVlIjoieUZWUmw4REROV2lqV1dJdzFJVit1d290OFE4WXJEZGlNbjB1bDlaRExlYlEvMkJMcmZadTRYRWdZRm1uWDRLbCIsIm1hYyI6IjNiODI1ODhkYjZmMTJhZjUzNjVlNTMwODlhYWRhNjc3NDZkMzE4ZDMxYzA1NmZjNTk1NDZmZWFjNzZjNGM4YjIiLCJ0YWciOiIifQ==', 
                                voucher_cover_link = '', 
                                voucher_cover_link_code = '', 
                                voucher_serial = 'VXU4AKQ1MFN', 
                                expiry_date = '2024-11-15', 
                                product = null, )
                            ], )
                    ]
            )
        else:
            return VOUCHERVRESPONSE(
        )
        """

    def testVOUCHERVRESPONSE(self):
        """Test VOUCHERVRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
