# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.api.products_api import ProductsApi


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()

    def tearDown(self) -> None:
        pass

    def test_get_list_of_products(self) -> None:
        """Test case for get_list_of_products

        Get all products master data
        """
        pass

    def test_get_product_detail(self) -> None:
        """Test case for get_product_detail

        Get product detail data
        """
        pass

    def test_get_stores_of_product(self) -> None:
        """Test case for get_stores_of_product

        Get stores of this product
        """
        pass


if __name__ == '__main__':
    unittest.main()
