# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.vouchersendsmsresponse import VOUCHERSENDSMSRESPONSE

class TestVOUCHERSENDSMSRESPONSE(unittest.TestCase):
    """VOUCHERSENDSMSRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VOUCHERSENDSMSRESPONSE:
        """Test VOUCHERSENDSMSRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VOUCHERSENDSMSRESPONSE`
        """
        model = VOUCHERSENDSMSRESPONSE()
        if include_optional:
            return VOUCHERSENDSMSRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = [
                    gotit_api_python_sdk.models.voucher_send_sms_schema.VOUCHER_SEND_SMS_SCHEMA(
                        voucher_link_code = '1gEGcntd', 
                        phone_no = '0394162063', 
                        receiver_nm = 'Got It', 
                        sender_nm = 'Got It', )
                    ]
            )
        else:
            return VOUCHERSENDSMSRESPONSE(
        )
        """

    def testVOUCHERSENDSMSRESPONSE(self):
        """Test VOUCHERSENDSMSRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
