"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.voucher_send_method_api import VoucherSendMethodApi  # noqa: E501


class TestVoucherSendMethodApi(unittest.TestCase):
    """VoucherSendMethodApi unit test stubs"""

    def setUp(self):
        self.api = VoucherSendMethodApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_status_zns(self):
        """Test case for check_status_zns

        Check status zns  # noqa: E501
        """
        pass

    def test_send_voucher_by_email(self):
        """Test case for send_voucher_by_email

        Send voucher by mail  # noqa: E501
        """
        pass

    def test_send_voucher_by_sms(self):
        """Test case for send_voucher_by_sms

        Send voucher by sms  # noqa: E501
        """
        pass

    def test_send_voucher_by_zns(self):
        """Test case for send_voucher_by_zns

        Send voucher by zns  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
