# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.requestsendvoucherbyzns import REQUESTSENDVOUCHERBYZNS

class TestREQUESTSENDVOUCHERBYZNS(unittest.TestCase):
    """REQUESTSENDVOUCHERBYZNS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> REQUESTSENDVOUCHERBYZNS:
        """Test REQUESTSENDVOUCHERBYZNS
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `REQUESTSENDVOUCHERBYZNS`
        """
        model = REQUESTSENDVOUCHERBYZNS()
        if include_optional:
            return REQUESTSENDVOUCHERBYZNS(
                phone_no = '0394162063',
                receiver_nm = 'Got It',
                voucher_serials = [
                    '1234567890123456'
                    ],
                transaction_id = 'transactionID'
            )
        else:
            return REQUESTSENDVOUCHERBYZNS(
                phone_no = '0394162063',
                voucher_serials = [
                    '1234567890123456'
                    ],
                transaction_id = 'transactionID',
        )
        """

    def testREQUESTSENDVOUCHERBYZNS(self):
        """Test REQUESTSENDVOUCHERBYZNS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
