"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.productpriceschema import PRODUCTPRICESCHEMA
from openapi_client.model.productv import PRODUCTV
globals()['PRODUCTPRICESCHEMA'] = PRODUCTPRICESCHEMA
globals()['PRODUCTV'] = PRODUCTV
from openapi_client.model.vouchervschema_vouchers import VOUCHERVSCHEMAVouchers


class TestVOUCHERVSCHEMAVouchers(unittest.TestCase):
    """VOUCHERVSCHEMAVouchers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOUCHERVSCHEMAVouchers(self):
        """Test VOUCHERVSCHEMAVouchers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOUCHERVSCHEMAVouchers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
