# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.productsdefaultlinkg import PRODUCTSDEFAULTLINKG

class TestPRODUCTSDEFAULTLINKG(unittest.TestCase):
    """PRODUCTSDEFAULTLINKG unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PRODUCTSDEFAULTLINKG:
        """Test PRODUCTSDEFAULTLINKG
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PRODUCTSDEFAULTLINKG`
        """
        model = PRODUCTSDEFAULTLINKG()
        if include_optional:
            return PRODUCTSDEFAULTLINKG(
                product_image = 'https://img-stg.gotit.vn/compress/580x580/2023/12/1703063556_Y4cEZ.png',
                link = 'https://v-stg.gotit.vn/zFrnkL7U',
                code = '0034317609',
                serial = 'VCA44DB9GFF',
                product_id = '1541',
                price_id = '2991',
                value = 50000,
                expired_date = '2023-12-30'
            )
        else:
            return PRODUCTSDEFAULTLINKG(
        )
        """

    def testPRODUCTSDEFAULTLINKG(self):
        """Test PRODUCTSDEFAULTLINKG"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
