# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.usagemethodschema import USAGEMETHODSCHEMA

class TestUSAGEMETHODSCHEMA(unittest.TestCase):
    """USAGEMETHODSCHEMA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> USAGEMETHODSCHEMA:
        """Test USAGEMETHODSCHEMA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `USAGEMETHODSCHEMA`
        """
        model = USAGEMETHODSCHEMA()
        if include_optional:
            return USAGEMETHODSCHEMA(
                type = 'AT_STORE',
                title = 'GotIt',
                description = 'GotIt',
                order = 1,
                link = '',
                phone_1 = '',
                phone_2 = ''
            )
        else:
            return USAGEMETHODSCHEMA(
        )
        """

    def testUSAGEMETHODSCHEMA(self):
        """Test USAGEMETHODSCHEMA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
