"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.vouchersendznsresponse_data import VOUCHERSENDZNSRESPONSEData
globals()['VOUCHERSENDZNSRESPONSEData'] = VOUCHERSENDZNSRESPONSEData
from openapi_client.model.vouchersendznsresponse import VOUCHERSENDZNSRESPONSE


class TestVOUCHERSENDZNSRESPONSE(unittest.TestCase):
    """VOUCHERSENDZNSRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOUCHERSENDZNSRESPONSE(self):
        """Test VOUCHERSENDZNSRESPONSE"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOUCHERSENDZNSRESPONSE()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
