"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.brands_api import BrandsApi  # noqa: E501


class TestBrandsApi(unittest.TestCase):
    """BrandsApi unit test stubs"""

    def setUp(self):
        self.api = BrandsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_brands_by_products(self):
        """Test case for brands_by_products

        Get brand by product  # noqa: E501
        """
        pass

    def test_get_detail_of_brand(self):
        """Test case for get_detail_of_brand

        Get brand detail  # noqa: E501
        """
        pass

    def test_get_list_of_brands(self):
        """Test case for get_list_of_brands

        Get list of brands  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
