# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.api.voucher_send_method_api import VoucherSendMethodApi


class TestVoucherSendMethodApi(unittest.TestCase):
    """VoucherSendMethodApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VoucherSendMethodApi()

    def tearDown(self) -> None:
        pass

    def test_check_status_zns(self) -> None:
        """Test case for check_status_zns

        Check status zns
        """
        pass

    def test_send_voucher_by_email(self) -> None:
        """Test case for send_voucher_by_email

        Send voucher by mail
        """
        pass

    def test_send_voucher_by_sms(self) -> None:
        """Test case for send_voucher_by_sms

        Send voucher by sms
        """
        pass

    def test_send_voucher_by_zns(self) -> None:
        """Test case for send_voucher_by_zns

        Send voucher by zns
        """
        pass


if __name__ == '__main__':
    unittest.main()
