# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.productg import PRODUCTG

class TestPRODUCTG(unittest.TestCase):
    """PRODUCTG unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PRODUCTG:
        """Test PRODUCTG
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PRODUCTG`
        """
        model = PRODUCTG()
        if include_optional:
            return PRODUCTG(
                product_image = 'https://img-stg.gotit.vn/compress/580x580/2023/10/1697689521_VQLZQ.png',
                link = 'https://v-stg.gotit.vn/CavXeYy4',
                code = '2630bec5',
                serial = 'V92Z57VNFGH',
                product_id = 2478,
                price_id = 10260,
                value = 100000,
                expired_date = '2023-12-30',
                partner = gotit_api_python_sdk.models.vendor_schema.VENDOR_SCHEMA(
                    expiry = '2024-01-08', 
                    vendor = 'SPE', )
            )
        else:
            return PRODUCTG(
        )
        """

    def testPRODUCTG(self):
        """Test PRODUCTG"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
