"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.vouchercheckznsresponse_data import VOUCHERCHECKZNSRESPONSEData
globals()['VOUCHERCHECKZNSRESPONSEData'] = VOUCHERCHECKZNSRESPONSEData
from openapi_client.model.vouchercheckznsresponse import VOUCHERCHECKZNSRESPONSE


class TestVOUCHERCHECKZNSRESPONSE(unittest.TestCase):
    """VOUCHERCHECKZNSRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOUCHERCHECKZNSRESPONSE(self):
        """Test VOUCHERCHECKZNSRESPONSE"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOUCHERCHECKZNSRESPONSE()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
