# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.productdetail import PRODUCTDETAIL

class TestPRODUCTDETAIL(unittest.TestCase):
    """PRODUCTDETAIL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PRODUCTDETAIL:
        """Test PRODUCTDETAIL
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PRODUCTDETAIL`
        """
        model = PRODUCTDETAIL()
        if include_optional:
            return PRODUCTDETAIL(
                product_id = 2782,
                product_nm = 'Thẻ Quà Tặng',
                product_img = 'https://img-stg.gotit.vn/compress/580x580/2023/06/1686628941_SakZB.png',
                product_sub_img = [https://img-stg.gotit.vn/compress/580x580/2023/06/1686628941_SakZB.png],
                brand_id = 46,
                brand_nm = 'Got It_Multi',
                product_type = 'c',
                brand_name_slug = 'got-it',
                brand_phone = '(+848) 3622 1022',
                brand_address = 'Lầu 6, Tòa nhà Khải Hoàn, 83B Hoàng Sa, P.Đakao, Q.1, TPHCM',
                brand_desc = '<p>Applicable in Ho Chi Minh City.<br>Not applicable for Super Tuesday – Discount 30% for all menu promotion.</p>',
                brand_service_guide = '<ul>\n\t<li>Sử dụng tương đương tiền mặt. Bạn có thể thanh toán thêm phần chênh lệch (nếu có)</li>\n\t<li>Dùng thanh toán tại cửa hàng hoặc mua hàng qua web/app/hotline, tùy từng thương hiệu</li>\n\t<li>Có thể áp dụng nhiều thẻ quà tặng cho một lần thanh toán tại hầu hết thương hiệu liên kết</li>\n\t<li>Mỗi thẻ quà tặng có quy định thời hạn sử dụng nhất định</li>\n</ul>',
                service_guide = '<p>- &Aacute;p dụng tại c&aacute;c thương hiệu đối t&aacute;c của Got It v&agrave; nạp tiền điện thoại. Vui l&ograve;ng xem chi tiết danh s&aacute;ch thương hiệu v&agrave; địa chỉ b&ecirc;n dưới.</p>\r\n',
                brand_logo = 'https://img-stg.gotit.vn/compress/brand/1687315597_GKMl1.png',
                link = 'https://v-stg.gotit.vn/phong-cach-song/got-it-multi/the-qua-tang-1541.html',
                prices = [
                    gotit_api_python_sdk.models.product_price_schema.PRODUCT_PRICE_SCHEMA(
                        price_id = 12258, 
                        price_nm = '1', 
                        price_value = 735000, )
                    ],
                name_slug = 'Got It eGift',
                product_desc = '<p>Qu&agrave; Tặng Got It được sử dụng dễ d&agrave;ng tại c&aacute;c cửa h&agrave;ng thuộc hệ thống đối t&aacute;c của Got It.&nbsp;</p>',
                product_short_desc = '<p>Thật nhanh ch&oacute;ng v&agrave; dễ d&agrave;ng để gửi tặng những m&oacute;n qu&agrave; s&agrave;nh điệu với Qu&agrave; Tặng Got It Đặc Biệt.</p>',
                terms = '<p>- Phiếu qu&agrave; tặng điện tử được cung cấp bởi Got It!</p><p>- Một ho&aacute; đơn c&oacute; thể sử dụng nhiều Phiếu qu&agrave; tặng, mỗi Phiếu qu&agrave; tặng c&oacute; gi&aacute; trị sử dụng 01 lần theo thời hạn quy định.</p>',
                category_id = 8,
                category_nm = 'Phong Cách Sống',
                category_img = 'https://img.gotit.vn/category/Lifestyle.png',
                brand_redeem = [
                    gotit_api_python_sdk.models.brand_reedem_schema.BRAND_REEDEM_SCHEMA(
                        brand_id = 1, 
                        brand_name = 'SUPERBOWL', 
                        brand_logo = 'https://img-stg.gotit.vn/compress/brand/1444997889_MP91v.png', 
                        brand_name_slug = 'superbowl', 
                        brand_phone = '(+848) 3848 8888', 
                        brand_address = 'A43 Trường Sơn, Phường 4 , Tân Bình, TP.HCM', 
                        brand_desc = 'SUPERBOWL', 
                        brand_service_guide = '<p>test service guide</p>', 
                        category_id = 1, 
                        category_nm = 'Nhà Hàng', 
                        category_img = 'https://img.gotit.vn/category/nha-hang.png', )
                    ],
                store_list = [
                    gotit_api_python_sdk.models.stores_schema.STORES_SCHEMA(
                        store_id = 3002, 
                        store_nm = 'anh16', 
                        store_addr = 'address_vi', 
                        store_em = 'null', 
                        store_ph = 'null', 
                        lat = 0, 
                        long = 0, 
                        brand_nm = 'Got It_Multi', 
                        district_id = 49, 
                        district_nm = 'Sóc Sơn', 
                        city_id = 2, 
                        city_nm = 'Hà Nội', )
                    ]
            )
        else:
            return PRODUCTDETAIL(
        )
        """

    def testPRODUCTDETAIL(self):
        """Test PRODUCTDETAIL"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
