# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.branddetail import BRANDDETAIL

class TestBRANDDETAIL(unittest.TestCase):
    """BRANDDETAIL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BRANDDETAIL:
        """Test BRANDDETAIL
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BRANDDETAIL`
        """
        model = BRANDDETAIL()
        if include_optional:
            return BRANDDETAIL(
                brand_id = 46,
                brand_nm = 'Got It_Multi',
                brand_addr = 'Lầu 6, Tòa nhà Khải Hoàn, 83B Hoàng Sa, P.Đakao, Q.1, TPHCM',
                brand_logo = 'https://img-stg.gotit.vn/compress/brand/1687315597_GKMl1.png',
                slug = 'got-it',
                short_desc = '',
                description = '<p>Applicable in Ho Chi Minh City.<br>Not applicable for Super Tuesday – Discount 30% for all menu promotion.</p>',
                category_id = [1,2,3,7,8,9,10],
                order = 0,
                service_guide = '',
                stores = [
                    gotit_api_python_sdk.models.stores_schema.STORES_SCHEMA(
                        store_id = 3002, 
                        store_nm = 'anh16', 
                        store_addr = 'address_vi', 
                        store_em = 'null', 
                        store_ph = 'null', 
                        lat = 0, 
                        long = 0, 
                        brand_nm = 'Got It_Multi', 
                        district_id = 49, 
                        district_nm = 'Sóc Sơn', 
                        city_id = 2, 
                        city_nm = 'Hà Nội', )
                    ],
                usage_methods = [
                    gotit_api_python_sdk.models.usage_method_schema.USAGE_METHOD_SCHEMA(
                        type = 'AT_STORE', 
                        title = 'GotIt', 
                        description = 'GotIt', 
                        order = 1, 
                        link = '', 
                        phone_1 = '', 
                        phone_2 = '', )
                    ]
            )
        else:
            return BRANDDETAIL(
        )
        """

    def testBRANDDETAIL(self):
        """Test BRANDDETAIL"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
