# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.categoriesresponse import CATEGORIESRESPONSE

class TestCATEGORIESRESPONSE(unittest.TestCase):
    """CATEGORIESRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CATEGORIESRESPONSE:
        """Test CATEGORIESRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CATEGORIESRESPONSE`
        """
        model = CATEGORIESRESPONSE()
        if include_optional:
            return CATEGORIESRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = [
                    gotit_api_python_sdk.models.categories_detail.CATEGORIES_DETAIL(
                        category_id = 3, 
                        category_nm = 'Mỹ Phẩm và Làm Đẹp', 
                        category_img = 'https://img.gotit.vn/category/my-pham-va-lam-dep.png', 
                        slug = 'fashion-cosmetic', 
                        order = 1, )
                    ]
            )
        else:
            return CATEGORIESRESPONSE(
        )
        """

    def testCATEGORIESRESPONSE(self):
        """Test CATEGORIESRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
