# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.brandreedemschema import BRANDREEDEMSCHEMA

class TestBRANDREEDEMSCHEMA(unittest.TestCase):
    """BRANDREEDEMSCHEMA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BRANDREEDEMSCHEMA:
        """Test BRANDREEDEMSCHEMA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BRANDREEDEMSCHEMA`
        """
        model = BRANDREEDEMSCHEMA()
        if include_optional:
            return BRANDREEDEMSCHEMA(
                brand_id = 1,
                brand_name = 'SUPERBOWL',
                brand_logo = 'https://img-stg.gotit.vn/compress/brand/1444997889_MP91v.png',
                brand_name_slug = 'superbowl',
                brand_phone = '(+848) 3848 8888',
                brand_address = 'A43 Trường Sơn, Phường 4 , Tân Bình, TP.HCM',
                brand_desc = 'SUPERBOWL',
                brand_service_guide = '<p>test service guide</p>',
                category_id = 1,
                category_nm = 'Nhà Hàng',
                category_img = 'https://img.gotit.vn/category/nha-hang.png'
            )
        else:
            return BRANDREEDEMSCHEMA(
        )
        """

    def testBRANDREEDEMSCHEMA(self):
        """Test BRANDREEDEMSCHEMA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
