# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.vouchercheckresponse import VOUCHERCHECKRESPONSE

class TestVOUCHERCHECKRESPONSE(unittest.TestCase):
    """VOUCHERCHECKRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VOUCHERCHECKRESPONSE:
        """Test VOUCHERCHECKRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VOUCHERCHECKRESPONSE`
        """
        model = VOUCHERCHECKRESPONSE()
        if include_optional:
            return VOUCHERCHECKRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = [
                    gotit_api_python_sdk.models.voucher_check_schema.VOUCHER_CHECK_SCHEMA(
                        transaction_ref_id = 'voucher_0711_102', 
                        vouchers = [
                            gotit_api_python_sdk.models.voucher_check_schema_detail.VOUCHER_CHECK_SCHEMA_DETAIL(
                                transaction_ref_id = '1000007_123abc', 
                                voucher_code = '4142468304', 
                                voucher_link = 'https://v-stg.gotit.vn/b51r4XtA', 
                                voucher_cover_link = '', 
                                voucher_serial = 'VXU4AKQ1MFN', 
                                group_link = 'https://e-stg.gotit.vn/gLsZaFRN', 
                                group_voucher_serial = 'E2V2RML6F52', 
                                group_cover_link = 'https://e-stg.gotit.vn/gLsZaFRN', 
                                voucher_link_code = 'b51r4XtA', 
                                voucher_image_link = 'https://v-stg.gotit.vn/save-voucher/vi/eyJpdiI6Ii80QVJaOXNmS0lBUmw3c283SjZ4amc9PSIsInZhbHVlIjoieUZWUmw4REROV2lqV1dJdzFJVit1d290OFE4WXJEZGlNbjB1bDlaRExlYlEvMkJMcmZadTRYRWdZRm1uWDRLbCIsIm1hYyI6IjNiODI1ODhkYjZmMTJhZjUzNjVlNTMwODlhYWRhNjc3NDZkMzE4ZDMxYzA1NmZjNTk1NDZmZWFjNzZjNGM4YjIiLCJ0YWciOiIifQ==', 
                                expiry_date = '2024-11-15', 
                                state_code = 3, 
                                state_text = 'Opened', 
                                used_store = [
                                    gotit_api_python_sdk.models.stores_schema.STORES_SCHEMA(
                                        store_id = 3002, 
                                        store_nm = 'anh16', 
                                        store_addr = 'address_vi', 
                                        store_em = 'null', 
                                        store_ph = 'null', 
                                        lat = 0, 
                                        long = 0, 
                                        brand_nm = 'Got It_Multi', 
                                        district_id = 49, 
                                        district_nm = 'Sóc Sơn', 
                                        city_id = 2, 
                                        city_nm = 'Hà Nội', )
                                    ], 
                                used_time = '', 
                                used_brand = 'Opened', 
                                product = gotit_api_python_sdk.models.product_v.PRODUCT_V(
                                    product_id = 1541, 
                                    product_nm = 'Thẻ Quà Tặng', 
                                    product_img = 'https://img-stg.gotit.vn/compress/580x580/2023/05/1684485240_oPTbk.png', 
                                    brand_id = 46, 
                                    brand_nm = 'Got It_Multi', 
                                    brand_service_guide = '<ul>\n\t<li>Sử dụng tương đương tiền mặt. Bạn có thể thanh toán thêm phần chênh lệch (nếu có)</li>\n\t<li>Dùng thanh toán tại cửa hàng hoặc mua hàng qua web/app/hotline, tùy từng thương hiệu</li>\n\t<li>Có thể áp dụng nhiều thẻ quà tặng cho một lần thanh toán tại hầu hết thương hiệu liên kết</li>\n\t<li>Mỗi thẻ quà tặng có quy định thời hạn sử dụng nhất định</li>\n</ul>', 
                                    link = 'https://v-stg.gotit.vn/phong-cach-song/got-it-multi/the-qua-tang-1541.html', 
                                    price = gotit_api_python_sdk.models.product_price_schema.PRODUCT_PRICE_SCHEMA(
                                        price_id = 12258, 
                                        price_nm = '1', 
                                        price_value = 735000, ), 
                                    product_desc = '', 
                                    terms = '<p>- Phiếu qu&agrave; tặng điện tử được cung cấp bởi Got It.</p>\r\n\r\n<p>- Một ho&aacute; đơn c&oacute; thể sử dụng nhiều Phiếu qu&agrave; tặng, mỗi Phiếu qu&agrave; tặng c&oacute; gi&aacute; trị sử dụng 01 lần theo thời hạn quy định.</p>\r\n\r\n<p>- Vui l&ograve;ng xuất tr&igrave;nh Phiếu qu&agrave; tặng trước khi thực hiện thanh to&aacute;n.</p>\r\n\r\n<p>- Phiếu qu&agrave; tặng c&oacute; thể &aacute;p dụng cho c&aacute;c sản phẩm hoặc dịch vụ kh&aacute;c c&ugrave;ng gi&aacute; trị khi sản phẩm/dịch vụ tr&ecirc;n Phiếu qu&agrave; tặng đ&atilde; hết h&agrave;ng.</p>\r\n\r\n<p>- Phiếu qu&agrave; tặng kh&ocirc;ng c&oacute; gi&aacute; trị quy đổi th&agrave;nh tiền mặt hoặc ho&agrave;n lại tiền hoặc b&aacute;n lại. Kh&aacute;ch h&agrave;ng sẽ trả th&ecirc;m tiền nếu sử dụng qu&aacute; gi&aacute; trị Phiếu qu&agrave; tặng.</p>\r\n\r\n<p>- Kh&aacute;ch h&agrave;ng tự bảo mật th&ocirc;ng tin m&atilde; qu&agrave; tặng sau khi mua.</p>\r\n\r\n<p>- M&atilde; qu&agrave; tặng sẽ kh&ocirc;ng được ho&agrave;n lại khi bị mất hoặc Đ&atilde; sử dụng.</p>\r\n\r\n<p>- Kh&aacute;ch h&agrave;ng vui l&ograve;ng li&ecirc;n hệ với nh&agrave; cung cấp khi c&oacute; thắc mắc hoặc khiếu nại li&ecirc;n quan đến chất lượng của sản phẩm/dịch vụ theo hotline 1900558820 hoặc support@gotit.vn.</p>\r\n', 
                                    product_type = 'c', 
                                    store_list = [
                                        gotit_api_python_sdk.models.store_product_schema.STORE_PRODUCT_SCHEMA(
                                            store_id = 3002, 
                                            store_nm = 'anh16', 
                                            store_addr = 'address_vi', 
                                            lat = 0, 
                                            long = 0, 
                                            phone = '(076)2479266', 
                                            city_id = 2, 
                                            city = 'Hà Nội', 
                                            dist_id = 49, 
                                            district = 'Sóc Sơn', )
                                        ], ), )
                            ], )
                    ]
            )
        else:
            return VOUCHERCHECKRESPONSE(
        )
        """

    def testVOUCHERCHECKRESPONSE(self):
        """Test VOUCHERCHECKRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
