# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.vouchersendznsresponse import VOUCHERSENDZNSRESPONSE

class TestVOUCHERSENDZNSRESPONSE(unittest.TestCase):
    """VOUCHERSENDZNSRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VOUCHERSENDZNSRESPONSE:
        """Test VOUCHERSENDZNSRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VOUCHERSENDZNSRESPONSE`
        """
        model = VOUCHERSENDZNSRESPONSE()
        if include_optional:
            return VOUCHERSENDZNSRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = gotit_api_python_sdk.models.voucher_send_zns_response_data.VOUCHER_SEND_ZNS_RESPONSE_data(
                    transaction_id = 'transactionID', )
            )
        else:
            return VOUCHERSENDZNSRESPONSE(
        )
        """

    def testVOUCHERSENDZNSRESPONSE(self):
        """Test VOUCHERSENDZNSRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
