"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.vouchercheckschemadetail import VOUCHERCHECKSCHEMADETAIL
globals()['VOUCHERCHECKSCHEMADETAIL'] = VOUCHERCHECKSCHEMADETAIL
from openapi_client.model.vouchercheckschema import VOUCHERCHECKSCHEMA


class TestVOUCHERCHECKSCHEMA(unittest.TestCase):
    """VOUCHERCHECKSCHEMA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOUCHERCHECKSCHEMA(self):
        """Test VOUCHERCHECKSCHEMA"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOUCHERCHECKSCHEMA()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
