"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.productpriceschema import PRODUCTPRICESCHEMA
from openapi_client.model.storesschema import STORESSCHEMA
globals()['PRODUCTPRICESCHEMA'] = PRODUCTPRICESCHEMA
globals()['STORESSCHEMA'] = STORESSCHEMA
from openapi_client.model.productsdetail import PRODUCTSDETAIL


class TestPRODUCTSDETAIL(unittest.TestCase):
    """PRODUCTSDETAIL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPRODUCTSDETAIL(self):
        """Test PRODUCTSDETAIL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PRODUCTSDETAIL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
