"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.brandreedemschema import BRANDREEDEMSCHEMA
from openapi_client.model.productpriceschema import PRODUCTPRICESCHEMA
from openapi_client.model.storesschema import STORESSCHEMA
globals()['BRANDREEDEMSCHEMA'] = BRANDREEDEMSCHEMA
globals()['PRODUCTPRICESCHEMA'] = PRODUCTPRICESCHEMA
globals()['STORESSCHEMA'] = STORESSCHEMA
from openapi_client.model.productdetail import PRODUCTDETAIL


class TestPRODUCTDETAIL(unittest.TestCase):
    """PRODUCTDETAIL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPRODUCTDETAIL(self):
        """Test PRODUCTDETAIL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PRODUCTDETAIL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
