# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.vouchersendemailresponse import VOUCHERSENDEMAILRESPONSE

class TestVOUCHERSENDEMAILRESPONSE(unittest.TestCase):
    """VOUCHERSENDEMAILRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VOUCHERSENDEMAILRESPONSE:
        """Test VOUCHERSENDEMAILRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VOUCHERSENDEMAILRESPONSE`
        """
        model = VOUCHERSENDEMAILRESPONSE()
        if include_optional:
            return VOUCHERSENDEMAILRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = [
                    gotit_api_python_sdk.models.voucher_send_email_schema.VOUCHER_SEND_EMAIL_SCHEMA(
                        voucher_link_code = '1gEGcntd', 
                        email = 'quang.huynh@gotit.vn', 
                        receiver_nm = 'Got It', 
                        sender_nm = 'Got It', 
                        message = 'Got It', )
                    ]
            )
        else:
            return VOUCHERSENDEMAILRESPONSE(
        )
        """

    def testVOUCHERSENDEMAILRESPONSE(self):
        """Test VOUCHERSENDEMAILRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
