"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.vouchersendznsresponse_data import VOUCHERSENDZNSRESPONSEData


class TestVOUCHERSENDZNSRESPONSEData(unittest.TestCase):
    """VOUCHERSENDZNSRESPONSEData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVOUCHERSENDZNSRESPONSEData(self):
        """Test VOUCHERSENDZNSRESPONSEData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VOUCHERSENDZNSRESPONSEData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
