# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.storeproductschema import STOREPRODUCTSCHEMA

class TestSTOREPRODUCTSCHEMA(unittest.TestCase):
    """STOREPRODUCTSCHEMA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> STOREPRODUCTSCHEMA:
        """Test STOREPRODUCTSCHEMA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `STOREPRODUCTSCHEMA`
        """
        model = STOREPRODUCTSCHEMA()
        if include_optional:
            return STOREPRODUCTSCHEMA(
                store_id = 3002,
                store_nm = 'anh16',
                store_addr = 'address_vi',
                lat = 0,
                long = 0,
                phone = '(076)2479266',
                city_id = 2,
                city = 'Hà Nội',
                dist_id = 49,
                district = 'Sóc Sơn'
            )
        else:
            return STOREPRODUCTSCHEMA(
        )
        """

    def testSTOREPRODUCTSCHEMA(self):
        """Test STOREPRODUCTSCHEMA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
