# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.api.voucher_status_api import VoucherStatusApi


class TestVoucherStatusApi(unittest.TestCase):
    """VoucherStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VoucherStatusApi()

    def tearDown(self) -> None:
        pass

    def test_check_voucher(self) -> None:
        """Test case for check_voucher

        Check voucher status
        """
        pass


if __name__ == '__main__':
    unittest.main()
