# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.vendorschema import VENDORSCHEMA

class TestVENDORSCHEMA(unittest.TestCase):
    """VENDORSCHEMA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VENDORSCHEMA:
        """Test VENDORSCHEMA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VENDORSCHEMA`
        """
        model = VENDORSCHEMA()
        if include_optional:
            return VENDORSCHEMA(
                expiry = '2024-01-08',
                vendor = 'SPE'
            )
        else:
            return VENDORSCHEMA(
        )
        """

    def testVENDORSCHEMA(self):
        """Test VENDORSCHEMA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
