# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.api.brands_api import BrandsApi


class TestBrandsApi(unittest.TestCase):
    """BrandsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrandsApi()

    def tearDown(self) -> None:
        pass

    def test_brands_by_products(self) -> None:
        """Test case for brands_by_products

        Get brand by product
        """
        pass

    def test_get_detail_of_brand(self) -> None:
        """Test case for get_detail_of_brand

        Get brand detail
        """
        pass

    def test_get_list_of_brands(self) -> None:
        """Test case for get_list_of_brands

        Get list of brands
        """
        pass


if __name__ == '__main__':
    unittest.main()
