"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.productsdetail import PRODUCTSDETAIL
globals()['PRODUCTSDETAIL'] = PRODUCTSDETAIL
from openapi_client.model.productsresponse_data_inner import PRODUCTSRESPONSEDataInner


class TestPRODUCTSRESPONSEDataInner(unittest.TestCase):
    """PRODUCTSRESPONSEDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPRODUCTSRESPONSEDataInner(self):
        """Test PRODUCTSRESPONSEDataInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PRODUCTSRESPONSEDataInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
