"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.storesschema import STORESSCHEMA
from openapi_client.model.usagemethodschema import USAGEMETHODSCHEMA
globals()['STORESSCHEMA'] = STORESSCHEMA
globals()['USAGEMETHODSCHEMA'] = USAGEMETHODSCHEMA
from openapi_client.model.branddetail import BRANDDETAIL


class TestBRANDDETAIL(unittest.TestCase):
    """BRANDDETAIL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBRANDDETAIL(self):
        """Test BRANDDETAIL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BRANDDETAIL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
