# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.storesresponse import STORESRESPONSE

class TestSTORESRESPONSE(unittest.TestCase):
    """STORESRESPONSE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> STORESRESPONSE:
        """Test STORESRESPONSE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `STORESRESPONSE`
        """
        model = STORESRESPONSE()
        if include_optional:
            return STORESRESPONSE(
                status = 'OK',
                status_code = 200,
                error = '',
                message = '',
                data = [
                    gotit_api_python_sdk.models.stores_response_data_inner.STORES_RESPONSE_data_inner(
                        store_list = [
                            gotit_api_python_sdk.models.stores_schema.STORES_SCHEMA(
                                store_id = 3002, 
                                store_nm = 'anh16', 
                                store_addr = 'address_vi', 
                                store_em = 'null', 
                                store_ph = 'null', 
                                lat = 0, 
                                long = 0, 
                                brand_nm = 'Got It_Multi', 
                                district_id = 49, 
                                district_nm = 'Sóc Sơn', 
                                city_id = 2, 
                                city_nm = 'Hà Nội', )
                            ], )
                    ]
            )
        else:
            return STORESRESPONSE(
        )
        """

    def testSTORESRESPONSE(self):
        """Test STORESRESPONSE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
