# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.requestcreatevoucherlinkg import REQUESTCREATEVOUCHERLINKG

class TestREQUESTCREATEVOUCHERLINKG(unittest.TestCase):
    """REQUESTCREATEVOUCHERLINKG unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> REQUESTCREATEVOUCHERLINKG:
        """Test REQUESTCREATEVOUCHERLINKG
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `REQUESTCREATEVOUCHERLINKG`
        """
        model = REQUESTCREATEVOUCHERLINKG()
        if include_optional:
            return REQUESTCREATEVOUCHERLINKG(
                product_list = [
                    gotit_api_python_sdk.models.product_default_link_g.PRODUCT_DEFAULT_LINK_G(
                        product_id = 1541, 
                        product_price_id = 2991, 
                        quantity = 1, )
                    ],
                order_name = 'Got It Promotion - Jul 2023',
                expiry_date = '2024-11-15',
                transaction_ref_id = '1000007_123abc',
                use_otp = 1,
                otp_type = 1,
                password = '123456',
                receiver_name = 'Quang Huynh',
                phone = '0394162063',
                email = 'quang.huynh@gotit.vn'
            )
        else:
            return REQUESTCREATEVOUCHERLINKG(
                product_list = [
                    gotit_api_python_sdk.models.product_default_link_g.PRODUCT_DEFAULT_LINK_G(
                        product_id = 1541, 
                        product_price_id = 2991, 
                        quantity = 1, )
                    ],
                order_name = 'Got It Promotion - Jul 2023',
                expiry_date = '2024-11-15',
                transaction_ref_id = '1000007_123abc',
        )
        """

    def testREQUESTCREATEVOUCHERLINKG(self):
        """Test REQUESTCREATEVOUCHERLINKG"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
