"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.categories_api import CategoriesApi  # noqa: E501


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_category_by_product(self):
        """Test case for get_category_by_product

        Get category by product  # noqa: E501
        """
        pass

    def test_get_list_of_categories(self):
        """Test case for get_list_of_categories

        Get lists category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
