# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gotit_api_python_sdk.models.storesschema import STORESSCHEMA

class TestSTORESSCHEMA(unittest.TestCase):
    """STORESSCHEMA unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> STORESSCHEMA:
        """Test STORESSCHEMA
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `STORESSCHEMA`
        """
        model = STORESSCHEMA()
        if include_optional:
            return STORESSCHEMA(
                store_id = 3002,
                store_nm = 'anh16',
                store_addr = 'address_vi',
                store_em = 'null',
                store_ph = 'null',
                lat = 0,
                long = 0,
                brand_nm = 'Got It_Multi',
                district_id = 49,
                district_nm = 'Sóc Sơn',
                city_id = 2,
                city_nm = 'Hà Nội'
            )
        else:
            return STORESSCHEMA(
        )
        """

    def testSTORESSCHEMA(self):
        """Test STORESSCHEMA"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
