# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from gotit_api_sdk_python.models.requestcheckstatuszns import REQUESTCHECKSTATUSZNS
from gotit_api_sdk_python.models.requestsendvoucherbyemail import REQUESTSENDVOUCHERBYEMAIL
from gotit_api_sdk_python.models.requestsendvoucherbysms import REQUESTSENDVOUCHERBYSMS
from gotit_api_sdk_python.models.requestsendvoucherbyzns import REQUESTSENDVOUCHERBYZNS
from gotit_api_sdk_python.models.vouchercheckznsresponse import VOUCHERCHECKZNSRESPONSE
from gotit_api_sdk_python.models.vouchersendemailresponse import VOUCHERSENDEMAILRESPONSE
from gotit_api_sdk_python.models.vouchersendsmsresponse import VOUCHERSENDSMSRESPONSE
from gotit_api_sdk_python.models.vouchersendznsresponse import VOUCHERSENDZNSRESPONSE

from gotit_api_sdk_python.api_client import ApiClient, RequestSerialized
from gotit_api_sdk_python.api_response import ApiResponse
from gotit_api_sdk_python.rest import RESTResponseType


class VoucherSendMethodApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def check_status_zns(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestcheckstatuszns: Optional[REQUESTCHECKSTATUSZNS] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> VOUCHERCHECKZNSRESPONSE:
        """Check status zns

        Check status zns

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestcheckstatuszns:
        :type requestcheckstatuszns: REQUESTCHECKSTATUSZNS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._check_status_zns_serialize(
            x_gi_authorization=x_gi_authorization,
            requestcheckstatuszns=requestcheckstatuszns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERCHECKZNSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def check_status_zns_with_http_info(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestcheckstatuszns: Optional[REQUESTCHECKSTATUSZNS] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[VOUCHERCHECKZNSRESPONSE]:
        """Check status zns

        Check status zns

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestcheckstatuszns:
        :type requestcheckstatuszns: REQUESTCHECKSTATUSZNS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._check_status_zns_serialize(
            x_gi_authorization=x_gi_authorization,
            requestcheckstatuszns=requestcheckstatuszns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERCHECKZNSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def check_status_zns_without_preload_content(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestcheckstatuszns: Optional[REQUESTCHECKSTATUSZNS] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Check status zns

        Check status zns

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestcheckstatuszns:
        :type requestcheckstatuszns: REQUESTCHECKSTATUSZNS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._check_status_zns_serialize(
            x_gi_authorization=x_gi_authorization,
            requestcheckstatuszns=requestcheckstatuszns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERCHECKZNSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _check_status_zns_serialize(
        self,
        x_gi_authorization,
        requestcheckstatuszns,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_gi_authorization is not None:
            _header_params['X-GI-Authorization'] = x_gi_authorization
        # process the form parameters
        # process the body parameter
        if requestcheckstatuszns is not None:
            _body_params = requestcheckstatuszns


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v4.0/vouchers/send/zns/check',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def send_voucher_by_email(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbyemail: Optional[REQUESTSENDVOUCHERBYEMAIL] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> VOUCHERSENDEMAILRESPONSE:
        """Send voucher by mail

        Send voucher by mail

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbyemail:
        :type requestsendvoucherbyemail: REQUESTSENDVOUCHERBYEMAIL
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_email_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbyemail=requestsendvoucherbyemail,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDEMAILRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def send_voucher_by_email_with_http_info(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbyemail: Optional[REQUESTSENDVOUCHERBYEMAIL] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[VOUCHERSENDEMAILRESPONSE]:
        """Send voucher by mail

        Send voucher by mail

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbyemail:
        :type requestsendvoucherbyemail: REQUESTSENDVOUCHERBYEMAIL
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_email_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbyemail=requestsendvoucherbyemail,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDEMAILRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def send_voucher_by_email_without_preload_content(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbyemail: Optional[REQUESTSENDVOUCHERBYEMAIL] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Send voucher by mail

        Send voucher by mail

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbyemail:
        :type requestsendvoucherbyemail: REQUESTSENDVOUCHERBYEMAIL
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_email_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbyemail=requestsendvoucherbyemail,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDEMAILRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _send_voucher_by_email_serialize(
        self,
        x_gi_authorization,
        requestsendvoucherbyemail,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_gi_authorization is not None:
            _header_params['X-GI-Authorization'] = x_gi_authorization
        # process the form parameters
        # process the body parameter
        if requestsendvoucherbyemail is not None:
            _body_params = requestsendvoucherbyemail


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v4.0/vouchers/send/email',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def send_voucher_by_sms(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbysms: REQUESTSENDVOUCHERBYSMS,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> VOUCHERSENDSMSRESPONSE:
        """Send voucher by sms

        Send voucher by sms

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbysms: (required)
        :type requestsendvoucherbysms: REQUESTSENDVOUCHERBYSMS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_sms_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbysms=requestsendvoucherbysms,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDSMSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def send_voucher_by_sms_with_http_info(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbysms: REQUESTSENDVOUCHERBYSMS,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[VOUCHERSENDSMSRESPONSE]:
        """Send voucher by sms

        Send voucher by sms

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbysms: (required)
        :type requestsendvoucherbysms: REQUESTSENDVOUCHERBYSMS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_sms_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbysms=requestsendvoucherbysms,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDSMSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def send_voucher_by_sms_without_preload_content(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbysms: REQUESTSENDVOUCHERBYSMS,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Send voucher by sms

        Send voucher by sms

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbysms: (required)
        :type requestsendvoucherbysms: REQUESTSENDVOUCHERBYSMS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_sms_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbysms=requestsendvoucherbysms,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDSMSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _send_voucher_by_sms_serialize(
        self,
        x_gi_authorization,
        requestsendvoucherbysms,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_gi_authorization is not None:
            _header_params['X-GI-Authorization'] = x_gi_authorization
        # process the form parameters
        # process the body parameter
        if requestsendvoucherbysms is not None:
            _body_params = requestsendvoucherbysms


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v4.0/vouchers/send/sms',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def send_voucher_by_zns(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbyzns: Optional[REQUESTSENDVOUCHERBYZNS] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> VOUCHERSENDZNSRESPONSE:
        """Send voucher by zns

        Send voucher by zns

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbyzns:
        :type requestsendvoucherbyzns: REQUESTSENDVOUCHERBYZNS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_zns_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbyzns=requestsendvoucherbyzns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDZNSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def send_voucher_by_zns_with_http_info(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbyzns: Optional[REQUESTSENDVOUCHERBYZNS] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[VOUCHERSENDZNSRESPONSE]:
        """Send voucher by zns

        Send voucher by zns

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbyzns:
        :type requestsendvoucherbyzns: REQUESTSENDVOUCHERBYZNS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_zns_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbyzns=requestsendvoucherbyzns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDZNSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def send_voucher_by_zns_without_preload_content(
        self,
        x_gi_authorization: Annotated[StrictStr, Field(description="Authorization")],
        requestsendvoucherbyzns: Optional[REQUESTSENDVOUCHERBYZNS] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Send voucher by zns

        Send voucher by zns

        :param x_gi_authorization: Authorization (required)
        :type x_gi_authorization: str
        :param requestsendvoucherbyzns:
        :type requestsendvoucherbyzns: REQUESTSENDVOUCHERBYZNS
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_voucher_by_zns_serialize(
            x_gi_authorization=x_gi_authorization,
            requestsendvoucherbyzns=requestsendvoucherbyzns,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "VOUCHERSENDZNSRESPONSE",
            '400': "HTTPBADREQUEST",
            '401': "HTTPUNAUTHORIZED",
            '404': "HTTPNOTFOUND",
            '500': "HTTPINTERNALSERVERERROR",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _send_voucher_by_zns_serialize(
        self,
        x_gi_authorization,
        requestsendvoucherbyzns,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_gi_authorization is not None:
            _header_params['X-GI-Authorization'] = x_gi_authorization
        # process the form parameters
        # process the body parameter
        if requestsendvoucherbyzns is not None:
            _body_params = requestsendvoucherbyzns


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v4.0/vouchers/send/zns',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


