# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gotit_api_sdk_python.models.vendorschema import VENDORSCHEMA
from typing import Optional, Set
from typing_extensions import Self

class PRODUCTG(BaseModel):
    """
    PRODUCTG
    """ # noqa: E501
    product_image: Optional[StrictStr] = None
    link: Optional[StrictStr] = None
    code: Optional[StrictStr] = None
    serial: Optional[StrictStr] = None
    product_id: Optional[StrictInt] = None
    price_id: Optional[StrictInt] = None
    value: Optional[StrictInt] = None
    expired_date: Optional[StrictStr] = None
    partner: Optional[VENDORSCHEMA] = None
    __properties: ClassVar[List[str]] = ["product_image", "link", "code", "serial", "product_id", "price_id", "value", "expired_date", "partner"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PRODUCTG from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of partner
        if self.partner:
            _dict['partner'] = self.partner.to_dict()
        # set to None if product_image (nullable) is None
        # and model_fields_set contains the field
        if self.product_image is None and "product_image" in self.model_fields_set:
            _dict['product_image'] = None

        # set to None if link (nullable) is None
        # and model_fields_set contains the field
        if self.link is None and "link" in self.model_fields_set:
            _dict['link'] = None

        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if serial (nullable) is None
        # and model_fields_set contains the field
        if self.serial is None and "serial" in self.model_fields_set:
            _dict['serial'] = None

        # set to None if product_id (nullable) is None
        # and model_fields_set contains the field
        if self.product_id is None and "product_id" in self.model_fields_set:
            _dict['product_id'] = None

        # set to None if price_id (nullable) is None
        # and model_fields_set contains the field
        if self.price_id is None and "price_id" in self.model_fields_set:
            _dict['price_id'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if expired_date (nullable) is None
        # and model_fields_set contains the field
        if self.expired_date is None and "expired_date" in self.model_fields_set:
            _dict['expired_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PRODUCTG from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "product_image": obj.get("product_image"),
            "link": obj.get("link"),
            "code": obj.get("code"),
            "serial": obj.get("serial"),
            "product_id": obj.get("product_id"),
            "price_id": obj.get("price_id"),
            "value": obj.get("value"),
            "expired_date": obj.get("expired_date"),
            "partner": VENDORSCHEMA.from_dict(obj["partner"]) if obj.get("partner") is not None else None
        })
        return _obj


