# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gotit_api_sdk_python.models.vouchersendznsresponse_data import VOUCHERSENDZNSRESPONSEData
from typing import Optional, Set
from typing_extensions import Self

class VOUCHERSENDZNSRESPONSE(BaseModel):
    """
    VOUCHERSENDZNSRESPONSE
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="HTTP response status")
    status_code: Optional[StrictInt] = Field(default=None, description="HTTP response status codes", alias="statusCode")
    error: Optional[StrictStr] = Field(default=None, description="Error code")
    message: Optional[StrictStr] = Field(default=None, description="Message Error")
    data: Optional[VOUCHERSENDZNSRESPONSEData] = None
    __properties: ClassVar[List[str]] = ["status", "statusCode", "error", "message", "data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VOUCHERSENDZNSRESPONSE from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VOUCHERSENDZNSRESPONSE from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "statusCode": obj.get("statusCode"),
            "error": obj.get("error"),
            "message": obj.get("message"),
            "data": VOUCHERSENDZNSRESPONSEData.from_dict(obj["data"]) if obj.get("data") is not None else None
        })
        return _obj


