"""
    Sample API

    Technical document APIs for API Version 4.  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.httpbadrequest import HTTPBADREQUEST
from openapi_client.model.httpinternalservererror import HTTPINTERNALSERVERERROR
from openapi_client.model.httpnotfound import HTTPNOTFOUND
from openapi_client.model.httpunauthorized import HTTPUNAUTHORIZED
from openapi_client.model.requestcreatevoucherlinke import REQUESTCREATEVOUCHERLINKE
from openapi_client.model.requestcreatevoucherlinkg import REQUESTCREATEVOUCHERLINKG
from openapi_client.model.requestcreatevoucherlinkv import REQUESTCREATEVOUCHERLINKV
from openapi_client.model.vouchereresponse import VOUCHERERESPONSE
from openapi_client.model.vouchergresponse import VOUCHERGRESPONSE
from openapi_client.model.vouchervresponse import VOUCHERVRESPONSE


class VoucherApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.create_voucher_link_e_endpoint = _Endpoint(
            settings={
                'response_type': (VOUCHERERESPONSE,),
                'auth': [],
                'endpoint_path': '/api/v4.0/vouchers/e',
                'operation_id': 'create_voucher_link_e',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'x_gi_authorization',
                    'requestcreatevoucherlinke',
                ],
                'required': [
                    'x_gi_authorization',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'x_gi_authorization':
                        (str,),
                    'requestcreatevoucherlinke':
                        (REQUESTCREATEVOUCHERLINKE,),
                },
                'attribute_map': {
                    'x_gi_authorization': 'X-GI-Authorization',
                },
                'location_map': {
                    'x_gi_authorization': 'header',
                    'requestcreatevoucherlinke': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.create_voucher_link_g_endpoint = _Endpoint(
            settings={
                'response_type': (VOUCHERGRESPONSE,),
                'auth': [],
                'endpoint_path': '/api/v4.0/vouchers/g',
                'operation_id': 'create_voucher_link_g',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'x_gi_authorization',
                    'requestcreatevoucherlinkg',
                ],
                'required': [
                    'x_gi_authorization',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'x_gi_authorization':
                        (str,),
                    'requestcreatevoucherlinkg':
                        (REQUESTCREATEVOUCHERLINKG,),
                },
                'attribute_map': {
                    'x_gi_authorization': 'X-GI-Authorization',
                },
                'location_map': {
                    'x_gi_authorization': 'header',
                    'requestcreatevoucherlinkg': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.create_voucher_link_v_endpoint = _Endpoint(
            settings={
                'response_type': (VOUCHERVRESPONSE,),
                'auth': [],
                'endpoint_path': '/api/v4.0/vouchers/v',
                'operation_id': 'create_voucher_link_v',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'x_gi_authorization',
                    'requestcreatevoucherlinkv',
                ],
                'required': [
                    'x_gi_authorization',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'x_gi_authorization':
                        (str,),
                    'requestcreatevoucherlinkv':
                        (REQUESTCREATEVOUCHERLINKV,),
                },
                'attribute_map': {
                    'x_gi_authorization': 'X-GI-Authorization',
                },
                'location_map': {
                    'x_gi_authorization': 'header',
                    'requestcreatevoucherlinkv': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )

    def create_voucher_link_e(
        self,
        x_gi_authorization,
        **kwargs
    ):
        """Create voucher link e  # noqa: E501

        Create voucher link e  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_voucher_link_e(x_gi_authorization, async_req=True)
        >>> result = thread.get()

        Args:
            x_gi_authorization (str): Authorization

        Keyword Args:
            requestcreatevoucherlinke (REQUESTCREATEVOUCHERLINKE): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            VOUCHERERESPONSE
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['x_gi_authorization'] = \
            x_gi_authorization
        return self.create_voucher_link_e_endpoint.call_with_http_info(**kwargs)

    def create_voucher_link_g(
        self,
        x_gi_authorization,
        **kwargs
    ):
        """Create voucher link g  # noqa: E501

        Create voucher link g  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_voucher_link_g(x_gi_authorization, async_req=True)
        >>> result = thread.get()

        Args:
            x_gi_authorization (str): Authorization

        Keyword Args:
            requestcreatevoucherlinkg (REQUESTCREATEVOUCHERLINKG): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            VOUCHERGRESPONSE
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['x_gi_authorization'] = \
            x_gi_authorization
        return self.create_voucher_link_g_endpoint.call_with_http_info(**kwargs)

    def create_voucher_link_v(
        self,
        x_gi_authorization,
        **kwargs
    ):
        """Create voucher link v  # noqa: E501

        Create voucher link v  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_voucher_link_v(x_gi_authorization, async_req=True)
        >>> result = thread.get()

        Args:
            x_gi_authorization (str): Authorization

        Keyword Args:
            requestcreatevoucherlinkv (REQUESTCREATEVOUCHERLINKV): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            VOUCHERVRESPONSE
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['x_gi_authorization'] = \
            x_gi_authorization
        return self.create_voucher_link_v_endpoint.call_with_http_info(**kwargs)

