# coding: utf-8

"""
    Sample API

    Technical document APIs for API Version 4.

    The version of the OpenAPI document: 4.0.0
    Contact: quang.huynh@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class STORESSCHEMA(BaseModel):
    """
    STORESSCHEMA
    """ # noqa: E501
    store_id: Optional[StrictInt] = Field(default=None, description="Store Id", alias="storeId")
    store_nm: Optional[StrictStr] = Field(default=None, description="Store Name", alias="storeNm")
    store_addr: Optional[StrictStr] = Field(default=None, description="Store Address", alias="storeAddr")
    store_em: Optional[StrictStr] = Field(default=None, description="Store Email", alias="storeEm")
    store_ph: Optional[StrictStr] = Field(default=None, description="Store Phone", alias="storePh")
    lat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Lat location on Google maps")
    long: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Long location on Google maps")
    brand_nm: Optional[StrictStr] = Field(default=None, description="Brand Name", alias="brandNm")
    district_id: Optional[StrictInt] = Field(default=None, description="District code (Got It identifier)", alias="districtId")
    district_nm: Optional[StrictStr] = Field(default=None, description="District name", alias="districtNm")
    city_id: Optional[StrictInt] = Field(default=None, description="City code (Got It identifier)", alias="cityId")
    city_nm: Optional[StrictStr] = Field(default=None, description="City name", alias="cityNm")
    __properties: ClassVar[List[str]] = ["storeId", "storeNm", "storeAddr", "storeEm", "storePh", "lat", "long", "brandNm", "districtId", "districtNm", "cityId", "cityNm"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of STORESSCHEMA from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if store_id (nullable) is None
        # and model_fields_set contains the field
        if self.store_id is None and "store_id" in self.model_fields_set:
            _dict['storeId'] = None

        # set to None if store_nm (nullable) is None
        # and model_fields_set contains the field
        if self.store_nm is None and "store_nm" in self.model_fields_set:
            _dict['storeNm'] = None

        # set to None if store_addr (nullable) is None
        # and model_fields_set contains the field
        if self.store_addr is None and "store_addr" in self.model_fields_set:
            _dict['storeAddr'] = None

        # set to None if store_em (nullable) is None
        # and model_fields_set contains the field
        if self.store_em is None and "store_em" in self.model_fields_set:
            _dict['storeEm'] = None

        # set to None if store_ph (nullable) is None
        # and model_fields_set contains the field
        if self.store_ph is None and "store_ph" in self.model_fields_set:
            _dict['storePh'] = None

        # set to None if lat (nullable) is None
        # and model_fields_set contains the field
        if self.lat is None and "lat" in self.model_fields_set:
            _dict['lat'] = None

        # set to None if long (nullable) is None
        # and model_fields_set contains the field
        if self.long is None and "long" in self.model_fields_set:
            _dict['long'] = None

        # set to None if brand_nm (nullable) is None
        # and model_fields_set contains the field
        if self.brand_nm is None and "brand_nm" in self.model_fields_set:
            _dict['brandNm'] = None

        # set to None if district_id (nullable) is None
        # and model_fields_set contains the field
        if self.district_id is None and "district_id" in self.model_fields_set:
            _dict['districtId'] = None

        # set to None if district_nm (nullable) is None
        # and model_fields_set contains the field
        if self.district_nm is None and "district_nm" in self.model_fields_set:
            _dict['districtNm'] = None

        # set to None if city_id (nullable) is None
        # and model_fields_set contains the field
        if self.city_id is None and "city_id" in self.model_fields_set:
            _dict['cityId'] = None

        # set to None if city_nm (nullable) is None
        # and model_fields_set contains the field
        if self.city_nm is None and "city_nm" in self.model_fields_set:
            _dict['cityNm'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of STORESSCHEMA from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "storeId": obj.get("storeId"),
            "storeNm": obj.get("storeNm"),
            "storeAddr": obj.get("storeAddr"),
            "storeEm": obj.get("storeEm"),
            "storePh": obj.get("storePh"),
            "lat": obj.get("lat"),
            "long": obj.get("long"),
            "brandNm": obj.get("brandNm"),
            "districtId": obj.get("districtId"),
            "districtNm": obj.get("districtNm"),
            "cityId": obj.get("cityId"),
            "cityNm": obj.get("cityNm")
        })
        return _obj


